# Generated by Django 6.0.1 on 2026-02-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_locopilot_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainname', models.CharField(max_length=200)),
                ('trainnumber', models.CharField(max_length=200)),
                ('startingstation', models.CharField(max_length=200)),
                ('endingstation', models.CharField(max_length=200)),
            ],
        ),
    ]
