# Generated by Django 6.0.1 on 2026-02-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_train'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='latitude',
            new_name='trainame',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='longitude',
        ),
    ]
