# Generated by Django 6.0.1 on 2026-02-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_latitude_camera_trainame_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locopilot',
            old_name='latitude',
            new_name='trainame',
        ),
        migrations.RemoveField(
            model_name='locopilot',
            name='longitude',
        ),
    ]
