# Generated by Django 6.0.1 on 2026-02-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_latitude_locopilot_trainame_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='trainame',
            new_name='trainname',
        ),
        migrations.RenameField(
            model_name='locopilot',
            old_name='trainame',
            new_name='trainname',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='longitude',
        ),
    ]
