# Generated by Django 6.0.1 on 2026-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_trainame_camera_trainname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awareness',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='awareness',
            name='time',
            field=models.TimeField(),
        ),
    ]
