# Generated by Django 6.0.1 on 2026-03-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_awareness_date_alter_awareness_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='trainname',
        ),
        migrations.RemoveField(
            model_name='locopilot',
            name='trainname',
        ),
        migrations.AddField(
            model_name='camera',
            name='TRAIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.train'),
        ),
        migrations.AddField(
            model_name='cameraalert',
            name='LOCOPILOT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.locopilot'),
        ),
        migrations.AddField(
            model_name='locopilot',
            name='TRAIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.train'),
        ),
    ]
